#!/bin/bash

set -e

if [ -e "${PWFILE}" ];then
	AUTH_DIRECTIVE="
	auth_basic \"Restricted\";
	auth_basic_user_file \"${PWFILE}\";
"
fi

cat >/etc/nginx.conf <<EOF
user ${APP_USER};
daemon off;
worker_processes 4;

events {
	worker_connections 786;
}

http {
	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	access_log /dev/stdout;
	error_log /dev/stderr;

	gzip on;
	gzip_disable "msie6";

	server {
		listen 80 default_server;

		root ${APP_HOME};
		autoindex on;

		client_max_body_size ${CLIENT_MAX_BODY_SIZE};

		$AUTH_DIRECTIVE

		location / {
			dav_methods PUT DELETE MKCOL COPY MOVE;
			dav_ext_methods PROPFIND OPTIONS;
			dav_access user:rw group:r all:r;
			create_full_put_path on;
		}
	}
}

EOF