#!/bin/bash

DOCKERHOST=$(ip route show | grep -e ^default | awk -F" " '{ print $3 }')

##
## setup defaults
##
SETUP_DIR="/docker/setup"

LOG_DIR="/var/log"

_setupRuntime() {
    # set up what has to be set up
    for i in `ls -A ${SETUP_DIR}`; do
        echo "Setting up $i..."
        source "${SETUP_DIR}/$i"
    done
}

echo "Setting up runtime environment..."
_setupRuntime

case "$1" in
    run|nginx)
        echo "Starting nginx..."
        /usr/sbin/nginx -c /etc/nginx.conf
        ;;
    lighttpd)
        echo "Starting lighttpd..."
        /usr/sbin/lighttpd -D -f /etc/lighttpd.conf
        ;;
    apache2)
        echo "Starting apache2..."
        /usr/sbin/apache2 -DFOREGROUND
        ;;
    *)
        exec su -l ${APP_USER} -c "cd ${APP_HOME};$@"
        ;;
esac

exit 0
